### PR TITLE
add distribution files

### LINKED ISSUE #178: add distribution
For easier distribution on CDN providers, we want to add the distribution files.

### PR DESCRIPTION
**Pull request by pkra**
* add dist/
* update gitignore
* update version
Resolves #178

### CODE REVIEW

**Comment by pkra** [comment]
Note: the version was bumped for a "dummy" release.

**Comment by dpvc** [comment]
Now that we are moving a11y into the core MathJax repository, do we still want to do this?

**Comment by pkra** [comment]
> Now that we are moving a11y into the core MathJax repository, do we still want to do this?

Yes. We want to provide new versions of this extension via CDNs (as well as package managers like npm).

**Comment by pkra** [comment]
Cf. https://github.com/mathjax/MathJax/issues/1727#issuecomment-293905732

**Comment by dpvc** [comment]
I've made the changes needed to the extensions to not use `cdn.mathjax.org`, though they haven't been merged (the PR's are there).  Do you want to wait with this PR until after that, or go ahead with this one now, and make a second PR with my changes later?

**Comment by pkra** [comment]
No problem.

**Pull request closed without merging**
