### PR TITLE
Version 1.2.0 with dist

### PR DESCRIPTION
**Pull request by dpvc**
Update versions to 1.1.1 and add the `dist` directory.

### CODE REVIEW

**Comment by pkra** [comment]
I would have gone with v1.2.0 but I don't mind. Otherwise LGTM.

**Comment by dpvc** [comment]
> I would have gone with v1.2.0

Probably right.  I just went with the version you had used earlier.  I will change it...

**Comment by dpvc** [comment]
OK, the versions are updated.

**Comment by pkra** [comment]
LGTM!

**Comment by dpvc** [comment]
Does anything else have to be done to make a 1.2 release?  (Tag, make a release, do anything for npm?) I'm not sure what the process is at this point.

**Pull request merged**
