### PR TITLE
Moves remaining lab files from cdn to rawgit.

### PR DESCRIPTION
**Pull request by zorkow**
Solves reopened issue #199 .

### CODE REVIEW

**Comment by pkra** [comment]
@zorkow I think you just pushed to the wrong branch.

**Comment by zorkow** [comment]
Darn! I've been mucking about with so many branches today...
That should have been for #208, right?
I'll fix it later tonight.

**Comment by zorkow** [comment]
Mess fixed. PTAL.

**Comment by pkra** [comment]
lgtm

**Pull request merged**
