### PR TITLE
on gh-pages use 3rd-party repository

### LINKED ISSUE #144: fix gh-pages
The extensions fail to load since we don't have include a local sre build in this repo.

Proposal: check the url and set [a11y] to the third party repo if on github.io.

### PR DESCRIPTION
**Pull request by pkra**
Fixes #144

### CODE REVIEW

**Comment by pkra** [comment]
Yikes. Sorry for auto-correcting of whitespace.

**Comment by dpvc** [comment]
How about setting `[SRE]` rather than `[a11y]` since it is only SRE that is not in the github directory?

**Comment by pkra** [comment]
> How about setting [SRE] rather than [a11y] since it is only SRE that is not in the github directory?

My rationale was that gh-pages should be a bit more stable and will likely only be updated upon releases.

But I'm happy to change it -- it's a 3/10 for me.

**Comment by pkra** [comment]
@dpvc *bump* would this be more than a 3/10 for you?

**Comment by dpvc** [comment]
No, `main.js` is fine.

**Comment by pkra** [comment]
I think you're thinking of the mathjax-node PR :-) This is about mathjax-a11y.

**Comment by dpvc** [comment]
Sorry, yes I was.  I think it is better to use `[SRE]` since we have in the past used the `github.io` pages to demo development features, which may not yet be in the release version on the CDN.  I know that we aren't doing much development here now, but if you set `[a11y]`, then really all you are getting is the demo page, not the actual extensions from `github.io`, so why pull the whole repo into it?

I'm probably 6/10 for this.

**Comment by pkra** [comment]
Thanks! I'll update the PR in the morning.

**Comment by pkra** [comment]
I've amended the commit. PTAL.

**Pull request merged**
